### ISSUE TITLE
add a link between user from the company managed by dolibarr and roles inside the setup

### ISSUE THREAD

**Issue by bilbo-the-hobbit** [ATM-Consulting/dolibarr_module_contactdefault#6]
Hello,

one missing functionality is to be able to configure in the module a link between user from the company managed by dolibarr and roles inside the setup.

This way when a customer is created it would fill automatically the contact by default for this customer

ex: 

if configured in the setup of the module

Penati Paola
Proposition commerciale - Commercial suivi proposition
Facture client - Responsable suivi facture client

Swaelens Jonathan
Projet - Contributeur

this would create a customer with 

Penati Paola -Proposition commerciale - Commercial suivi proposition
Penati Paola - Facture client - Responsable suivi facture client

Swaelens Jonathan  - Projet - Contributeur

Cheers

**Comment by atm-john** [comment]
Module is déprecated
